# Generated by Django 5.0 on 2024-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('cognom', models.CharField(max_length=20)),
                ('cognom2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('curs', models.CharField(max_length=20)),
                ('moduls', models.CharField(max_length=20)),
            ],
        ),
    ]
