# Generated by Django 5.0 on 2024-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('professor', 'Professor'), ('alumne', 'Alumne')], max_length=20),
        ),
    ]
